### ISSUE TITLE
Can't use journald because systemd python package is outdated

### ISSUE THREAD

**Issue by AchmadFathoni** [freqtrade/freqtrade#8187]
## Describe your environment

  * Operating system: Arch Linux
  * Python Version:  3.10.0
  * CCXT version: 2.7.12
  * Freqtrade Version: 2023.1

## Describe the problem:
Using `--logifle journald` after installing systemd python package as stated in [manual](https://www.freqtrade.io/en/stable/advanced-setup/#logging-to-journald) will produce python error.

### Steps to reproduce:

  1. Install systemd python package `pip install systemd`
  2. Run the bot `freqtrade trade --logfile journald`
  
### Observed Results:

  * What happened? Bot throw error and stop working. systemd python package version is old and only works with python 3.6. The new package by same author has  renamed as `cysystemd`.
  * What did you expect to happen? Bot will run without error while sending log to journald.

### Relevant code exceptions or logs
```
2023-02-19 22:04:58,298 - freqtrade - INFO - freqtrade 2023.1
2023-02-19 22:04:58,424 - freqtrade.worker - INFO - Starting worker 2023.1
2023-02-19 22:04:58,424 - freqtrade.configuration.load_config - INFO - Using config: config.json ...
2023-02-19 22:04:58,426 - freqtrade.loggers - INFO - Verbosity set to 0
2023-02-19 22:04:58,426 - freqtrade.commands.trade_commands - ERROR - module 'collections' has no attribute 'Mapping'
2023-02-19 22:04:58,426 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/run/media/toni/Windows/Shared/Source/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/run/media/toni/Windows/Shared/Source/freqtrade/freqtrade/worker.py", line 37, in __init__
    self._init(False)
  File "/run/media/toni/Windows/Shared/Source/freqtrade/freqtrade/worker.py", line 50, in _init
    self._config = Configuration(self._args, None).get_config()
  File "/run/media/toni/Windows/Shared/Source/freqtrade/freqtrade/configuration/configuration.py", line 42, in get_config
    self.config = self.load_config()
  File "/run/media/toni/Windows/Shared/Source/freqtrade/freqtrade/configuration/configuration.py", line 84, in load_config
    self._process_logging_options(config)
  File "/run/media/toni/Windows/Shared/Source/freqtrade/freqtrade/configuration/configuration.py", line 125, in _process_logging_options
    setup_logging(config)
  File "/run/media/toni/Windows/Shared/Source/freqtrade/freqtrade/loggers.py", line 132, in setup_logging
    logger.info('Verbosity set to %s', verbosity)
  File "/home/toni/.mamba/envs/freqtrade/lib/python3.10/logging/__init__.py", line 1468, in info
    self._log(INFO, msg, args, **kwargs)
  File "/home/toni/.mamba/envs/freqtrade/lib/python3.10/logging/__init__.py", line 1615, in _log
    self.handle(record)
  File "/home/toni/.mamba/envs/freqtrade/lib/python3.10/logging/__init__.py", line 1625, in handle
    self.callHandlers(record)
  File "/home/toni/.mamba/envs/freqtrade/lib/python3.10/logging/__init__.py", line 1687, in callHandlers
    hdlr.handle(record)
  File "/home/toni/.mamba/envs/freqtrade/lib/python3.10/logging/__init__.py", line 967, in handle
    self.emit(record)
  File "/home/toni/.mamba/envs/freqtrade/lib/python3.10/site-packages/systemd/journal.py", line 147, in emit
    if isinstance(args, collections.Mapping):
AttributeError: module 'collections' has no attribute 'Mapping'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/run/media/toni/Windows/Shared/Source/freqtrade/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
  File "/run/media/toni/Windows/Shared/Source/freqtrade/freqtrade/commands/trade_commands.py", line 21, in start_trading
    logger.error(str(e))
  File "/home/toni/.mamba/envs/freqtrade/lib/python3.10/logging/__init__.py", line 1497, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/home/toni/.mamba/envs/freqtrade/lib/python3.10/logging/__init__.py", line 1615, in _log
    self.handle(record)
  File "/home/toni/.mamba/envs/freqtrade/lib/python3.10/logging/__init__.py", line 1625, in handle
    self.callHandlers(record)
  File "/home/toni/.mamba/envs/freqtrade/lib/python3.10/logging/__init__.py", line 1687, in callHandlers
    hdlr.handle(record)
  File "/home/toni/.mamba/envs/freqtrade/lib/python3.10/logging/__init__.py", line 967, in handle
    self.emit(record)
  File "/home/toni/.mamba/envs/freqtrade/lib/python3.10/site-packages/systemd/journal.py", line 147, in emit
    if isinstance(args, collections.Mapping):
AttributeError: module 'collections' has no attribute 'Mapping'
```
Note: Please copy/paste text of the messages, no screenshots of logs please.

**Comment by AchmadFathoni** [comment]
I've tried to simply repalce `systemd` module with `cysystemd`. The bot can run but this skipped test from `tests/test_configuration.py` fails

```
    def test_set_loggers_journald(mocker):
        logger = logging.getLogger()
        orig_handlers = logger.handlers
        logger.handlers = []
    
        config = {'verbosity': 2,
                  'logfile': 'journald',
                  }
    
        setup_logging(config)
        assert len(logger.handlers) == 2
        assert [x for x in logger.handlers if type(x).__name__ == "JournaldLogHandler"]
>       assert [x for x in logger.handlers if type(x) == logging.StreamHandler]
E       assert []

```

**Comment by xmatthias** [comment]
if you're keen on using journald/systemd logging - best provide a PR fixing this (it seems like you did some investigation into this).

my personal "fix" would probably be to drop journald support completely - as in my opinion, systemd/journald logging provides no benefit over regular file logging.
That's even more true once you're running more than one bot on a system, where you can no longer really differentiate which bot the log is coming from.

If you see benefits, best provide a PR fixing / updating what needs updating. 
My fix (probably in a few weeks) will be to remove support for journald otherwise.

**Comment by AchmadFathoni** [comment]
Yeah I think you should drop it completely. I just following tutorial to try thing out.

**Comment by xmatthias** [comment]
don't get me wrong - it's great to have it pointed out that it's not working the way we explain it.

journald logging was always an edge-case scenario - one i suspect very little people actually used (apparently, as it's not working).
My understanding was that you've got a usecase for this - but apparently that's not the case.
