### ISSUE TITLE
cannot import name 'NaN' from 'numpy' in version 2025.6 and 2025.7 stable

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#12062]
## Describe your environment

  * Operating system: Windows Server 2025, Docker Desktop, Ubuntu WSL
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2025.7 stable (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

With Freqtrade versions 2025.6 and 2025.7 stable I get the error:
cannot import name 'NaN' from 'numpy'

. . .while 2025.5 and below do not show any issues with the same strategy.

I found older posts with a similar case, I prefer, to post my problem separately, since there have been a lot of nympy versions in the meantime.

Is this a case, of adapting the docker file, prior of image build?

Mine currently looks like this (even I don't use FreqAI for now):
(This file works perfectly with Freqtrade 2025.5 and below)

FROM freqtradeorg/freqtrade:stable_freqaitorch
RUN pip install ta
RUN pip install pandas_ta
RUN pip install finta
RUN freqtrade install-ui

Can you please post the line(s) needed, in addition, for me?

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/)*

**Comment by stash86** [comment]
Numpy change their code. Now you need to use np.nan instead

**Comment by myNextCoder** [comment]
I thank you :)
The thing is, I only have np.nan in my strategy and at the top: import numpy as np
What do I need to change in addition?

**Comment by stash86** [comment]
I don't see anyone reporting such issue, so it might be possible that one of the additional libraries you installed manually there need to update their code as well

**Comment by xmatthias** [comment]
> cannot import name 'NaN' from 'numpy' 

That's caused by a code as follows: `from numpy import NaN`.
you'll either have that in your strategy - or in a dependency of your strategy - neither of which we control.

**Comment by myNextCoder** [comment]
Ok, I see. There is no
from numpy import NaN
present. For testing, I have created a new container. I have only one strategy file. The characters NaN are not present, only nan
I let you know if
"BBU_20_2.0": bbands_20_2["BBU_20_2.0"] if isinstance(bbands_20_2, pd.DataFrame) else np.nan,
. . .is responsable for the issue.
If ever the issue persits, I eliminate unnecessary lines from the file, to show you :)

**Comment by xmatthias** [comment]
no it's not. numpy renamed NaN to nan ... and that's what the change is about.

**Comment by myNextCoder** [comment]
I am absolutely with you, since stash86 informed me concerning this :)
. . .so I have to test further, I let you know more asap.

**Comment by myNextCoder** [comment]
I have discovered, that in my case the error message

cannot import name 'NaN' from 'numpy' in version 2025.6 and 2025.7

comes from the declaration

import pandas_ta as pta

The error even occurs in an empty strategy, as soon as the declaration is present.
Since I see quite a lot of strategies with this declaration, I ask you, if there is a fix, or, if one should switch from pta.tema to ta.TEMA

**Comment by xmatthias** [comment]
This would seem like you're manually installing pandas_ta - which will overwrite our fix for this.

freqtrade no longer installs pandas_ta - but `ft-pandas-ta` - which has this error patched.
In the end, it's the fault of your manual image - not something we can help you with.
