### ISSUE TITLE
cannot import name 'MAX_MESSAGE_LENGTH' from 'telegram'

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#8111]
## Describe your environment

  * Operating system: Windows Server 2022
  * Python Version: Miniconda
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: stable 2023.1 and 2023.2 dev____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

With both above declared Freqtrade versions my bot stops immediately after the start. I did not update from a previous version. I installed from the scratch, freshly. I install Freqtrade since 2020.12, and this error is new to me.

`2023-02-04 19:33:07,642 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.telegram ...
2023-02-04 19:33:07,673 - freqtrade.commands.trade_commands - ERROR - cannot import name 'MAX_MESSAGE_LENGTH' from 'telegram' (C:\Users\a9\.conda\envs\freqtrade\lib\site-packages\telegram\__init__.py)
2023-02-04 19:33:07,673 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "C:\Users\a9\Freqtrade\freqtrade\commands\trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "C:\Users\a9\Freqtrade\freqtrade\worker.py", line 37, in __init__
    self._init(False)
  File "C:\Users\a9\Freqtrade\freqtrade\worker.py", line 53, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "C:\Users\a9\Freqtrade\freqtrade\freqtradebot.py", line 84, in __init__
    self.rpc: RPCManager = RPCManager(self)
  File "C:\Users\a9\Freqtrade\freqtrade\rpc\rpc_manager.py", line 29, in __init__
    from freqtrade.rpc.telegram import Telegram
  File "C:\Users\a9\Freqtrade\freqtrade\rpc\telegram.py", line 20, in <module>
    from telegram import (MAX_MESSAGE_LENGTH, CallbackQuery, InlineKeyboardButton, InlineKeyboardMarkup,
ImportError: cannot import name 'MAX_MESSAGE_LENGTH' from 'telegram' (C:\Users\a9\.conda\envs\freqtrade\lib\site-packages\telegram\__init__.py)`

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
the only reason you can be receiving this is if the telegram version doesn't match the one in requirements.

please run `pip install -r requirements.txt` (with activated conda env).

**Comment by myNextCoder** [comment]
I thank you, currently there is an issue after some minutes of this installation:

` talib/_ta_lib.c(745): fatal error C1083: Cannot open include file: 'ta_libc.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.31.31103\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for TA-Lib
  Building wheel for tornado (setup.py) ... done
  Created wheel for tornado: filename=tornado-6.1-cp310-cp310-win_amd64.whl size=419575 sha256=350b1d5f76786541acfebc4cad30953a06247ddd59fcd367aaaee107d094b91f
  Stored in directory: c:\users\a1\appdata\local\pip\cache\wheels\80\32\8d\21cf0fa6ee4e083f6530e5b83dfdfa9489a3890d320803f4c7
Successfully built tornado
Failed to build TA-Lib
ERROR: Could not build wheels for TA-Lib, which is required to install pyproject.toml-based projects`

Beside possibly update the Visual Studio Build tools, do you think, there is another reason for failure?

**Comment by xmatthias** [comment]
this error now sounds like you didn't follow the [windows install](https://www.freqtrade.io/en/latest/windows_installation/) ...
which makes me wonder - how did you actually install ?

**Comment by myNextCoder** [comment]
I have executed your commands in the conda promt, one times outside of Freqtrade, and one times inside of Freqtrade. The error occured in both variations. If you have any hint, I am glad. I think, I will uninstall VS build tools and conda, and reinstall them. By the way, I have updated telegram, which is open in the same machine, a few hours before this issue. Other bots, with 2022.11 still run, but when I even reinstall 2022.11 I have the same telegram issue.

**Comment by xmatthias** [comment]
well if you follow the windows install guide - you shouldn't even need the vs build tools ...

**Comment by myNextCoder** [comment]
I have setup a Windows machine without VS build tools, with the current miniconda version. Installed 2023.1 stable. With: conda env create -n freqtrade-conda -f environment.yml, according to Freqtrade.io. The issue remains, before and also after running the command: pip install --upgrade telegram. Finally I also run the following commands:
pip uninstall telegram
and then:
pip install telegram

The log:

`2023-02-04 22:34:08,564 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.telegram ...
2023-02-04 22:34:08,564 - freqtrade.commands.trade_commands - ERROR - cannot import name 'MAX_MESSAGE_LENGTH' from 'telegram' (C:\Users\a1\.conda\envs\freqtrade-conda\lib\site-packages\telegram\__init__.py)
2023-02-04 22:34:08,564 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "C:\Users\a1\Freqtrade\freqtrade\commands\trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "C:\Users\a1\Freqtrade\freqtrade\worker.py", line 37, in __init__
    self._init(False)
  File "C:\Users\a1\Freqtrade\freqtrade\worker.py", line 53, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "C:\Users\a1\Freqtrade\freqtrade\freqtradebot.py", line 84, in __init__
    self.rpc: RPCManager = RPCManager(self)
  File "C:\Users\a1\Freqtrade\freqtrade\rpc\rpc_manager.py", line 29, in __init__
    from freqtrade.rpc.telegram import Telegram
  File "C:\Users\a1\Freqtrade\freqtrade\rpc\telegram.py", line 20, in <module>
    from telegram import (MAX_MESSAGE_LENGTH, CallbackQuery, InlineKeyboardButton, InlineKeyboardMarkup,
ImportError: cannot import name 'MAX_MESSAGE_LENGTH' from 'telegram' (C:\Users\a1\.conda\envs\freqtrade-conda\lib\site-packages\telegram\__init__.py)`

**Comment by xmatthias** [comment]
Seems like conda is installing the wrong telegram.

I'd suggest to try a non-conda installation as linked in the [windows install documentation](https://www.freqtrade.io/en/latest/windows_installation/).
It'll NOT require vs build tools if the instructions are followed properly.

The conda environment file doesn't properly pin the version (it's not a format that can be automatically updated).
We'll upper-limit the version for now - so the conda install on develop will work soon again.

**Comment by myNextCoder** [comment]
Yes, I am about to roll out a non-conda-related installation.

**Comment by gustab-kamil** [comment]
If anyone faced "MAX_MESSAGE_LENGTH" on linux, check if your _python-telegram-bot_ library version is fine, I had to downgrade mine to 13.14 to work with telegram_send 0.34.
